name = "Lixou"
profile-picture = "GitHub"
bio = "German developer kiddo. Sometimes streaming game development with rust and bevy"
github = "DasLixou"
discord = "DasLixou#2385"
discord-userid = "527112167963492393"
mastodon = "@lixou@toot.community"
